# Generated by Django 4.1.5 on 2023-01-06 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subdivision',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.subdivision'),
        ),
    ]
