# Generated by Django 4.0.5 on 2022-06-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
