# Generated by Django 4.0.5 on 2022-07-02 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('forms', '0003_rename_answers_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AddField(
            model_name='formwithanswer',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to='users.user'),
        ),
        migrations.AlterField(
            model_name='formwithanswer',
            name='about_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_user_set', to='users.user'),
        ),
    ]
