# Generated by Django 4.1.5 on 2023-01-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
