# Generated by Django 4.1.5 on 2023-01-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_formtemplate_description_formtemplate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='rating',
            field=models.IntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], default=5),
        ),
    ]
